### PR TITLE
Fixed parent locales

### PR DESCRIPTION
**Pull request by natemueller**
This is the result of my import after adding support for parentLocales in ruby-cldr.  The update:locales_resources target produced a lot more changes then I expected so I split this into two commits.  In the first I ran the update with an unmodified ruby-cldr.  Then I switched to my patched one and ran it again.

I have a feeling that the changes in the first commit are wrong and shouldn't be merged.  I haven't been able to figure out what caused them so I can't say for sure.  I'm submitted this for feedback+discussion.  I assume it can't be merged as-is but I don't know how to get it into a mergeable state.

### CODE REVIEW

**Comment by camertron** [comment]
Hmm... it is a bit weird that there are so many changes. The plural changes look to be related to some work that was done a while ago to improve plural accuracy. It's possible I didn't have the most up-to-date version of the cldr-plurals gem when I last ran the `update:locales_resources` target.

The other changes are surprising, but I'll bet they were caused by the new locale fallback logic you added. Hard to believe there were _that_ many changes tho. I'll investigate.

**Comment by natemueller** [comment]
The changes in the first commit were all from running update:locales_resources with the unmodified camertron/ruby-cldr.  They aren't related to my changes.  I changed the Gemfile, bundle installed and re-raked for the second commit.  I went through those changes and feel good about them.

**Comment by camertron** [comment]
Ok, that's good enough for me. Any thoughts about what kind of release this should be? I can see it as either a patch (could be considered a bug fix) or a minor version bump.

**Comment by natemueller** [comment]
Combined with #203 it feels like a minor version bump, but I don't have a strong preference.

**Comment by camertron** [comment]
Published as v4.2.0

**Pull request merged**
