### PR TITLE
Fix default options value for NumberDataReader#format_number.

### PR DESCRIPTION
**Pull request by KL-7**

### CODE REVIEW

**Comment by camertron** [comment]
Oops, nice catch :shaved_ice:

**Comment by KL-7** [comment]
Good thing it didn't really cause any issues. Still no idea what I was thinking when I did this in the first place :O

**Comment by camertron** [comment]
Did you originally do the work on this or was it me?

**Comment by KL-7** [comment]
The class itself was introduced by you, but I did some refactoring to support pluralization in abbreviated numbers and that's when this weird default happened. My bad.

**Pull request merged**
