### PR TITLE
Drop Ruby 1.8 support

### PR DESCRIPTION
**Pull request by KL-7**
There's one TODO left in `Component#to_utf8` method that I'm not sure about. I tried using the alternative that is proposed there, but it broke quite a few tests, because the resulting UTF8 representation is different. 

@camertron, is it safe to do that and just update the tests with whatever the new returned values are?

### CODE REVIEW

**Comment by KL-7** [comment]
Also, I'm going to convert everything to 1.9 hash syntax in a separate pull request.

**Comment by KL-7** [comment]
I reverted resource changes for now so it's easier to review. I'll update them again later to remove all quotes.

**Comment by caniszczyk** [comment]
Look how fast that build is now :)

**Comment by camertron** [comment]
@KL-7 should just be a matter of fixing the tests. The failures I saw when uncommenting that line in `component.rb` were just octal vs hex escape sequences. For example, Ruby 1.8 can only handle sequences like `\141` in regexes, while later versions support unicode escapes like `\u{0061}`. I fixed the tests and pushed my changes up to this branch, you should be good to go.

**Comment by KL-7** [comment]
Oh, nice, thank you @camertron!

**Pull request merged**
