### PR TITLE
Update to CLDR v32 and add locales [mk, es-ES] and update [es-419]

### PR DESCRIPTION
**Pull request by bherila**

### CODE REVIEW

**Comment by camertron** [comment]
Hey @bherila, thank you for this Herculean effort! Unfortunately I'm in the process right now of updating the library to CLDR v35.1, which is the most recent CLDR release. If things don't work out I'll take another look at this PR, but for now I'd like to shoot for the latest and greatest.

**Comment by bherila** [comment]
@camertron no worries, also seeing as the CLA has glitched and marked me with an X even though I've signed it. Do you think the update to v35 will happen relatively soon? Happy to wait and/or help you out if needed. 

Side note, do you think you could include/update [this list of locales](https://gist.github.com/bherila/6c7fc3996dc1252a948a84d7b6ffb2b5) as that'll prevent me from sending another PR and would be an absolutely HUGE help to me 😁 

Thank you very much for the quick response!

**Comment by camertron** [comment]
@bherila please see my comments on https://github.com/twitter/twitter-cldr-rb/issues/225. Yes, I'm hoping to be able to release v35 support as soon as I can get all the tests to pass.

**Comment by bherila** [comment]
Sounds good, thanks again!!

**Pull request closed without merging**
