### PR TITLE
Use new Travis CI infrastructure

### PR DESCRIPTION
**Pull request by caniszczyk**
This should speed up builds potentially

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

Signed-off-by: Chris Aniszczyk <zx@twitter.com>

### CODE REVIEW

**Comment by KL-7** [comment]
I didn't read through the whole thing yet, but this might be also helpful:
> The best news for open source projects is that our build caching is now available for them too. That means faster build speeds by caching dependencies. Make sure to read the docs before trying it out.

> For Ruby projects, it's as simple as adding cache: bundler to your .travis.yml.

**Comment by KL-7** [comment]
Could you also replace MRI 2.1.0 with 2.2.0? Hopefully it doesn't fail. Also, looks like JRuby and Rubinius are the slowest runtimes in our build. I still think we should keep JRuby, but I'm ok with dropping Rubinius until we hear from someone who's actually using TwitterCLDR on Rubinius.

**Comment by caniszczyk** [comment]
Will do!

It definitely looks like the build speeds up significantly with these changes.

**Comment by camertron** [comment]
I concur!

**Comment by KL-7** [comment]
Oh well, somehow bundler fails to install `ruby-cldr` on MRI 2.2.0. Feel free to revert it to `2.1.0` and merge, I can look into `2.2.0` issue later.

**Comment by camertron** [comment]
We shouldn't even need ruby-cldr when running tests, and it's in the `:development` group. Why is bundler loading it?

**Comment by KL-7** [comment]
Looks like removing our custom rubygems installation fixes the issue. I'll update the PR in a second. 

FYI, according to [this](https://github.com/bundler/bundler/issues/1552#issuecomment-4014684) even if you use `--without` bundler will download the excluded gems.

**Comment by KL-7** [comment]
Whoa, aside from JRuby, the whole build takes less than 5 minutes to run! Thanks for addressing this issue, @caniszczyk.

JRuby still needs some love though (#124).

**Comment by caniszczyk** [comment]
sweet! should we merge this in given that jruby-head is an acceptable failure for now?

**Pull request merged**
