### PR TITLE
Add en-001

### PR DESCRIPTION
**Pull request by alex-stripe**
I followed the instructions in the readme.

The `mri` run (2.6.3) went smoothly, but the jruby run seemed to download cldr_v21, which was unexpected. So if that isn't right, this might need an update.

This is an important locale for us at Stripe because it allows us to serve english emails with currency formatters that don't assume you use `$` as your currency symbol for USD (as a specific instance). It's the locale for the entire english speaking world.

Thanks! Let me know if there's something else I should run to make the jruby stuff have a different output.

### CODE REVIEW

**Comment by SlexAxton** [comment]
(Also, due to some weirdness i didn't diagnose in my laptop before sending this, I sent a fork from my personal account, slexaxton, as a PR from my work account, alex-stripe, but just wanted to note that I still control both accounts and all the commits were from a single user.)

**Comment by SlexAxton** [comment]
And if it's helpful, this is for my employer ✨stripe ✨.

**Comment by camertron** [comment]
@SlexAxton nice, thank you!

The JRuby-based importers downloaded CLDR v21 because unfortunately our collation implementation is based on it. I haven't had the time to dig into upgrading to later versions, which changed the format of the collation rules significantly.

**Comment by camertron** [comment]
Published as v5.4.0.

**Comment by SlexAxton** [comment]
ah, great. thanks for the speed and explanation! <3

**Comment by SlexAxton** [comment]
just as a note that i think `en-001` didn't exist until cldr-v26 or so, so there won't be collation rules for it in v21. (english already kinda works by default everywhere, and you already have en-150 in the same state)

Not a huge worry or anything, but figured I'd mention it.

**Comment by camertron** [comment]
Ah ok that makes sense :)

**Pull request merged**
